---
title: "homework"
output: html_document
date: "2022-10-06"
---
## load library

```{r}
library(sf)
library(tidyverse) 
```

## Data loading

```{r}

shape <- st_read("D:/CASA/CASA_0005/Week_1/New Zealand/statsnz-territorial-authority-2018-generalised-SHP/territorial-authority-2018-generalised.shp")

# dTolerance is the distance in which any “wiggles” will be straightened
shape_simple <- st_simplify(shape, dTolerance = 1000)

employed_2018 <- read_csv("D:/CASA/CASA_0005/Week_1/New Zealand/employee.csv")


# added test to last row to make character for example
Datatypelist <- shape_simple %>% 
  summarise_all(class)
Datatypelist


Datatypelist2 <- employed_2018 %>%
  summarise_all(class)
Datatypelist

summary(shape_simple)

shape_simple %>%
  st_geometry()%>%
  plot()
```
## Data manipulation 
join on the description 

```{r}
# join on the description 

shape2 <- shape_simple%>%
  merge(.,
        employed_2018,
        by.x="TA2018_V1_", 
        by.y="Territorial_authority_code")
```

Join on the ID by making the column numeric
```{r}
employed_2018 <- employed_2018 %>%
  mutate(Territorial_authority_code=(as.numeric(Territorial_authority_code)))

shape3 <- shape_simple %>%
  mutate(TA2018_V1_=(as.numeric(TA2018_V1_)))%>%
  merge(.,
        employed_2018,
        by.x="TA2018_V1_", 
        by.y="Territorial_authority_code")

Datatypelist <- shape3 %>% 
  summarise_all(class)
Datatypelist


Datatypelist2 <- employed_2018 %>%
  summarise_all(class)
Datatypelist

#or 

# shape3 <- shape %>%
#   transform(., TA2018_V1_ = as.numeric(TA2018_V1_))%>%
#   merge(.,
#         employed_2018,
#         by.x="TA2018_V1_", 
#         by.y="Area_Code")

# or also 
#shape$TA2018_V1_ = as.numeric(shape$TA2018_V1_)
```

## Data mapping

```{r}
library(tmap)
tmap_mode("plot")
# change the fill to your column name if different
my_map<-shape3 %>%
  qtm(.,fill = "Paid employee")

my_map
```


